In [1]:
import pandas as pd
#Importo la libreria

In [2]:
url = "https://raw.githubusercontent.com/luciamoralesandreo-netizen/Proyecto-google-colab/main/tipos_de_cambio.csv"
#Importo el git con el csv

In [3]:
df= pd.read_csv(url)
#Saca los primeros datos del CSV

In [4]:
df.head()

  Moneda  Tipo_de_cambio
0    EUR            1.00
1    AED            4.14
2    AFN           72.89
3    ALL           92.10
4    AMD          410.77

In [12]:
print("Maximo:", df['Tipo_de_cambio'].max())
print("Minimo:", df['Tipo_de_cambio'].min())
print("Media:", df['Tipo_de_cambio'].mean())
print("Mediana:", df['Tipo_de_cambio'].median())
print("Número de datos:", df['Tipo_de_cambio'].count())
print("Rango:", (df['Tipo_de_cambio'].max()- df['Tipo_de_cambio'].min()))
print("Varianza:", df['Tipo_de_cambio'].var())
print("Desviacion típica:", df['Tipo_de_cambio'].std())
print("Primer cuartil:", df['Tipo_de_cambio'].quantile(0.25))
print("Tercer cuartil:", df['Tipo_de_cambio'].quantile(0.75))
print("Rango intercuantílico:", (df['Tipo_de_cambio'].quantile(0.75) - df['Tipo_de_cambio'].quantile(0.25)))

Maximo: 1931942.72
Minimo: 0.0278
Media: 13426.157781927712
Mediana: 25.775
Número de datos: 166
Rango: 1931942.6922
Varianza: 22520282627.125694
Desviacion típica: 150067.59352746911
Primer cuartil: 3.4175
Tercer cuartil: 198.63750000000002
Rango intercuantílico: 195.22000000000003

In [13]:
df['Tipo_de_cambio'].describe()
#Otra forma de sacar los datos estadisticos mas facil

count    1.660000e+02
mean     1.342616e+04
std      1.500676e+05
min      2.780000e-02
25%      3.417500e+00
50%      2.577500e+01
75%      1.986375e+02
max      1.931943e+06
Name: Tipo_de_cambio, dtype: float64

In [18]:
moneda_max= df.loc[df['Tipo_de_cambio'].idxmax()]
print("Moneda con mayor tipo de cambio:", moneda_max)
moneda_min= df.loc[df['Tipo_de_cambio'].idxmin()]
print("Moneda con menor tipo de cambio:", moneda_min)

Moneda con mayor tipo de cambio: Moneda                   IRR
Tipo_de_cambio    1931942.72
Name: 67, dtype: object
Moneda con menor tipo de cambio: Moneda               CLF
Tipo_de_cambio    0.0278
Name: 29, dtype: object

In [22]:
!git clone https://github.com/luciamoralesandreo-netizen/Proyecto-google-colab.git

Cloning into 'Proyecto-google-colab'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.

In [23]:
%cd /content/Proyecto-google-colab/

/content/Proyecto-google-colab

In [24]:
!ls

tipos_de_cambio.csv

In [28]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [29]:
!find "/content/drive/MyDrive" -name "Estadistica csv.ipynb"

/content/drive/MyDrive/Colab Notebooks/Estadistica csv.ipynb

In [30]:
!cp "/content/drive/MyDrive/Colab Notebooks/Estadistica csv.ipynb"

cp: missing destination file operand after '/content/drive/MyDrive/Colab Notebooks/Estadistica csv.ipynb'
Try 'cp --help' for more information.

In [31]:
!ls

tipos_de_cambio.csv